### ISSUE TITLE
1.60.1 fails to build on macOS

### ISSUE THREAD

**Issue by mohd-akram** [libguestfs/libguestfs#386]
I get this error when trying to build:

```
launch-direct.c:881:5: error: use of undeclared identifier 'execvpe'
  881 |     execvpe (data->qemu, argv, env);        /* Run qemu. */
```

Elsewhere in the project, this is mentioned:

https://github.com/libguestfs/libguestfs/blob/6b592035130cde2501921f3861693ceb143591cb/lib/command.c#L621-L623

**Comment by rwmjones** [comment]
Introduced in commit 503e9fde5a:
```diff
-    execve (g->hv, argv, env);        /* Run qemu. */
-    perror (g->hv);
+    execvpe (data->qemu, argv, env);        /* Run qemu. */
+    perror (data->qemu);
```

This was because the `->qemu` field is now a name (searched on `$PATH`) instead of a complete path.

**Comment by rwmjones** [comment]
I posted a possible fix but I need to test it a bit myself first.
https://github.com/libguestfs/libguestfs/pull/388
